[flake8]

max-line-length = 120

exclude =
    .git,
    __pycache__,
    .venv,
    venv,
    env,
    .env

extend-ignore =
    W391,
    W292

per-file-ignores =
    features/steps/*.py:F403,F405,E302,E501